# config for yuqing's diary

title: "Yuqing's Diary"
email: "linyuqing97@gmail.com"
repository: "linyuqing97/yuqing-s-Diary"
description: "This is my personal profile website!!!"
logo: "/assets/images/myLogo.png"

twitter_username: yuqinglin
github_username: linyuqing97
minimal_mistakes_skin: air
search: true
breadcrumbs: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone:  https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#Site mashhead title
masthead_title: Yuqing Lin


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Yuqing Lin"
  avatar : "/assets/images/myLogo.png"
  bio    : "Computer Science Student from Binghamton"
  location: New York 
  links:
    - label: "Resume"
      icon: "fas fa-fw fa-link"
      url:  "https://linyuqing97.github.io/Leetcode/assets/docs/Resume.pdf"
  # - label: "Twitter"
  #    icon: "fab fa-fw fa-twitter-square"
  #    url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/linyuqing97"
   # - label: "Instagram"
   #  icon: "fab fa-fw fa-instagram"
   #   url: "https://instagram.com/"

footer:
  
  links:
  #  - label: "Twitter"
   #   icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/"
    #- label: "GitHub"
    #  icon: "fab fa-fw fa-github"
    #  url: "https://github.com/linyuqing97"
    
#   - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      #author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
